# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marine.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='marine.proto',
  package='CodeBattle',
  serialized_pb='\n\x0cmarine.proto\x12\nCodeBattle\"\x1f\n\x07Vector2\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01z\x18\x02 \x02(\x02\"\"\n\nVector2Int\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01z\x18\x02 \x02(\x05\"\xce\x01\n\x06Marine\x12\n\n\x02id\x18\x01 \x02(\x05\x12\n\n\x02hp\x18\x02 \x02(\x05\x12%\n\x08position\x18\x03 \x02(\x0b\x32\x13.CodeBattle.Vector2\x12\"\n\x06status\x18\x04 \x02(\x0e\x32\x12.CodeBattle.Status\x12+\n\x0etargetPosition\x18\x05 \x01(\x0b\x32\x13.CodeBattle.Vector2\x12\x14\n\x0c\x66laresAmount\x18\x06 \x01(\x05\x12\x1e\n\x04role\x18\x07 \x01(\x0e\x32\x10.CodeBattle.Role*@\n\x06Status\x12\x08\n\x04Idle\x10\x00\x12\x07\n\x03Run\x10\x01\x12\n\n\x06\x46lares\x10\x02\x12\r\n\tGunAttack\x10\x03\x12\x08\n\x04\x44\x65\x61\x64\x10\x04*-\n\x04Role\x12\n\n\x06Normal\x10\x00\x12\x0c\n\x08\x41ttacker\x10\x01\x12\x0b\n\x07Injured\x10\x02')

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='CodeBattle.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Idle', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Run', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Flares', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GunAttack', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Dead', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=306,
  serialized_end=370,
)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='CodeBattle.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Normal', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Attacker', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Injured', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=372,
  serialized_end=417,
)

Role = enum_type_wrapper.EnumTypeWrapper(_ROLE)
Idle = 0
Run = 1
Flares = 2
GunAttack = 3
Dead = 4
Normal = 0
Attacker = 1
Injured = 2



_VECTOR2 = _descriptor.Descriptor(
  name='Vector2',
  full_name='CodeBattle.Vector2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='CodeBattle.Vector2.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='CodeBattle.Vector2.z', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=59,
)


_VECTOR2INT = _descriptor.Descriptor(
  name='Vector2Int',
  full_name='CodeBattle.Vector2Int',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='CodeBattle.Vector2Int.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='CodeBattle.Vector2Int.z', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=95,
)


_MARINE = _descriptor.Descriptor(
  name='Marine',
  full_name='CodeBattle.Marine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CodeBattle.Marine.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='CodeBattle.Marine.hp', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='CodeBattle.Marine.position', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='CodeBattle.Marine.status', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetPosition', full_name='CodeBattle.Marine.targetPosition', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flaresAmount', full_name='CodeBattle.Marine.flaresAmount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='CodeBattle.Marine.role', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=304,
)

_MARINE.fields_by_name['position'].message_type = _VECTOR2
_MARINE.fields_by_name['status'].enum_type = _STATUS
_MARINE.fields_by_name['targetPosition'].message_type = _VECTOR2
_MARINE.fields_by_name['role'].enum_type = _ROLE
DESCRIPTOR.message_types_by_name['Vector2'] = _VECTOR2
DESCRIPTOR.message_types_by_name['Vector2Int'] = _VECTOR2INT
DESCRIPTOR.message_types_by_name['Marine'] = _MARINE

class Vector2(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VECTOR2

  # @@protoc_insertion_point(class_scope:CodeBattle.Vector2)

class Vector2Int(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VECTOR2INT

  # @@protoc_insertion_point(class_scope:CodeBattle.Vector2Int)

class Marine(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MARINE

  # @@protoc_insertion_point(class_scope:CodeBattle.Marine)


# @@protoc_insertion_point(module_scope)
